easy_admin:
    formats:
        date:     'd/m/Y'
        time:     'H:i'
        datetime: 'd/m/Y H:i:s'
    entities:
        Category:
            class: App\Entity\Category
            label: 'Catégories'
            form:  # <-- 'form' is applied to both 'new' and 'edit' views
                fields:
                    - 'Name'
                    - 'IsActive'
                    - 'IsStatic'

        Announcement:
            class: App\Entity\Announcement
            label: 'Annonces'
            form:  # <-- 'form' is applied to both 'new' and 'edit' views
                fields:
                    - 'Title'
                    - 'Cylindrical'
                    - 'Description'
                    - 'DatePublish'
                    - 'IsActive'
                    - 'IsPermisA2'
                    - 'Price'
                    - { property: 'Image1', type: 'file_upload', type_options: { upload_dir: 'templates/imagesmotos/' } }
                    - { property: 'Image2', type: 'file_upload', type_options: { upload_dir: 'templates/imagesmotos/' } }
                    - { property: 'Image3', type: 'file_upload', type_options: { upload_dir: 'templates/imagesmotos/' } }
                    - { property: 'Image4', type: 'file_upload', type_options: { upload_dir: 'templates/imagesmotos/' } }
                    - 'Category'
                    - 'User'

        User:
            class: App\Entity\User
            label: 'Utilisateurs'
            form:  # <-- 'form' is applied to both 'new' and 'edit' views
                fields:
                    - 'FirstName'
                    - 'LastName'
                    - 'Phone'
                    - 'Password'
                    - 'Email'
                    - 'Address'
                    - 'CodePoste'
                    - 'City'
                    - 'IsActive'
                    - 'IsPro'
                    
        StaticPage:
            class: App\Entity\StaticPage
            label: 'Pages Statiques'
            form:
                fields:
                    - 'Content'
                    - 'Category'