swiftmailer:
    transport: gmail
    username: ''
    password: ''
    auth_mode: login
    disable_delivery: true
    encryption: tls
    port: 465
    host: smtp.gmail.com
    spool: { type: 'memory' }
