# See https://symfony.com/doc/current/email/dev_environment.html
swiftmailer:
    # send all emails to a specific address
    # contact@box-racing.fr
    delivery_addresses: ['k.alonso292@gmail.com']
    #transport: gmail
    #username: k.alonso292@gmail.com
    #password: 'aqw78929'
    #auth_mode: oauth
    #disable_delivery: false
    #encryption: tls
    #port: 465
    #host: smtp.gmail.com
    #spool: { type: 'memory' }
